modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="moremekasuitmodules"
version="1.0.0"
displayName="MekanismMoreMekaSuitModules"
authors="sddsd2332"

description='''${mod_description}'''
[[dependencies.moremekasuitmodules]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.moremekasuitmodules]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"